info:
  Description: MS for Prosegur's SmartCash Loader
server:
  port: 8080
database: postgresql
spring:
  application:
    name: minuapp
  #datasource:
    #driverClassName: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/minuapp
    #username: postgres
    #password: password
  cloud:
    gcp:
      sql:
        database-name: minuappdb
        instance-connection-name: prosegur-scl:us-central1:minuappdb
      project-id: prosegur-scl
  datasource:
    initialization-mode: always
    username: postgres
    password: password
  profiles:
    active: postgresql
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 986862737807-5mhnhqe5opp8dljfdqvse8fhg1ls9c11.apps.googleusercontent.com
            client-secret: WwLHsYGWZjih4a32XTC0YBo5