info:
  Description: MS for Prosegur's SmartCash Loader
server:
  port: 8080
database: postgresql
spring:
  application:
    name: minuapp
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://34.66.125.210:5432/minuapp
    username: postgres
    password: password