swagger: '2.0'
info:
  title: Cloud Endpoints + Cloud Run
  description: Sample API on Cloud Endpoints with a Cloud Run backend
  version: 1.0.0
host: minuappservice-rzicdxfx4q-uc.a.run.app
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://minuappservice-rzicdxfx4q-uc.a.run.app
  protocol: h2
paths:
  /hi:
    get:
      summary: Greet a user
      operationId: hello
      responses:
        '200':
          description: A successful response
          schema:
            type: string